# tests/sql_reserved_words.py

"""
Reserved words of every database engine planetGen runs on, as data for
`test_sql_portability.py` (TEST.6). A reserved word can't be an unquoted
table, column, index, constraint name or alias on that engine; quoted in
backticks it can. Regenerate a list when CI adds an engine version.

How each list was produced (2026-10-01):

- `MYSQL_80`: MySQL 8.0.46's own list,
  `SELECT WORD FROM INFORMATION_SCHEMA.KEYWORDS WHERE RESERVED = 1`
  (262 words). Cross-checked with the probe used for MariaDB below,
  which found exactly the same 262 words on that server.
- `MYSQL_84_ADDED`: the words MySQL 8.4 made reserved, from the 8.4
  manual's "New Keywords and Reserved Words in MySQL 8.4" (marked (R)
  there). No 8.4 server was at hand; none of these is even a keyword on
  8.0.46 (absent from its INFORMATION_SCHEMA.KEYWORDS). 8.4 reserves no
  word 8.0 didn't, apart from these.
- `MARIADB`: MariaDB 10.11.14, measured. MariaDB's
  information_schema.KEYWORDS has no RESERVED column, so for every word
  in it and in MySQL 8.0's KEYWORDS (833 words) the probe ran
  `SELECT 1 AS <word>` and `CREATE TEMPORARY TABLE t (<word> INT)` and
  kept the words either statement rejected with a syntax error (1064).
  Both probes rejected the same 245 words. No MariaDB 11.x additions
  are included: none were found that could be confirmed (CI's 11.4 run
  of this test's own SQL is the check).
"""

MYSQL_80 = frozenset("""
ACCESSIBLE ADD ALL ALTER ANALYZE AND AS ASC ASENSITIVE BEFORE BETWEEN BIGINT BINARY BLOB BOTH BY
CALL CASCADE CASE CHANGE CHAR CHARACTER CHECK COLLATE COLUMN CONDITION CONSTRAINT CONTINUE
CONVERT CREATE CROSS CUBE CUME_DIST CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER
CURSOR DATABASE DATABASES DAY_HOUR DAY_MICROSECOND DAY_MINUTE DAY_SECOND DEC DECIMAL DECLARE
DEFAULT DELAYED DELETE DENSE_RANK DESC DESCRIBE DETERMINISTIC DISTINCT DISTINCTROW DIV DOUBLE
DROP DUAL EACH ELSE ELSEIF EMPTY ENCLOSED ESCAPED EXCEPT EXISTS EXIT EXPLAIN FALSE FETCH
FIRST_VALUE FLOAT FLOAT4 FLOAT8 FOR FORCE FOREIGN FROM FULLTEXT FUNCTION GENERATED GET GRANT
GROUP GROUPING GROUPS HAVING HIGH_PRIORITY HOUR_MICROSECOND HOUR_MINUTE HOUR_SECOND IF IGNORE IN
INDEX INFILE INNER INOUT INSENSITIVE INSERT INT INT1 INT2 INT3 INT4 INT8 INTEGER INTERSECT
INTERVAL INTO IO_AFTER_GTIDS IO_BEFORE_GTIDS IS ITERATE JOIN JSON_TABLE KEY KEYS KILL LAG
LAST_VALUE LATERAL LEAD LEADING LEAVE LEFT LIKE LIMIT LINEAR LINES LOAD LOCALTIME LOCALTIMESTAMP
LOCK LONG LONGBLOB LONGTEXT LOOP LOW_PRIORITY MASTER_BIND MASTER_SSL_VERIFY_SERVER_CERT MATCH
MAXVALUE MEDIUMBLOB MEDIUMINT MEDIUMTEXT MIDDLEINT MINUTE_MICROSECOND MINUTE_SECOND MOD MODIFIES
NATURAL NOT NO_WRITE_TO_BINLOG NTH_VALUE NTILE NULL NUMERIC OF ON OPTIMIZE OPTIMIZER_COSTS
OPTION OPTIONALLY OR ORDER OUT OUTER OUTFILE OVER PARTITION PERCENT_RANK PRECISION PRIMARY
PROCEDURE PURGE RANGE RANK READ READS READ_WRITE REAL RECURSIVE REFERENCES REGEXP RELEASE RENAME
REPEAT REPLACE REQUIRE RESIGNAL RESTRICT RETURN REVOKE RIGHT RLIKE ROW ROWS ROW_NUMBER SCHEMA
SCHEMAS SECOND_MICROSECOND SELECT SENSITIVE SEPARATOR SET SHOW SIGNAL SMALLINT SPATIAL SPECIFIC
SQL SQLEXCEPTION SQLSTATE SQLWARNING SQL_BIG_RESULT SQL_CALC_FOUND_ROWS SQL_SMALL_RESULT SSL
STARTING STORED STRAIGHT_JOIN SYSTEM TABLE TERMINATED THEN TINYBLOB TINYINT TINYTEXT TO TRAILING
TRIGGER TRUE UNDO UNION UNIQUE UNLOCK UNSIGNED UPDATE USAGE USE USING UTC_DATE UTC_TIME
UTC_TIMESTAMP VALUES VARBINARY VARCHAR VARCHARACTER VARYING VIRTUAL WHEN WHERE WHILE WINDOW WITH
WRITE XOR YEAR_MONTH ZEROFILL
""".split())

MYSQL_84_ADDED = frozenset("""
MANUAL PARALLEL QUALIFY TABLESAMPLE
""".split())

MARIADB = frozenset("""
ACCESSIBLE ADD ALL ALTER ANALYZE AND AS ASC ASENSITIVE BEFORE BETWEEN BIGINT BINARY BLOB BOTH BY
CALL CASCADE CASE CHANGE CHAR CHARACTER CHECK COLLATE COLUMN CONDITION CONSTRAINT CONTINUE
CONVERT CREATE CROSS CURRENT_DATE CURRENT_ROLE CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER
CURSOR DATABASES DAY_HOUR DAY_MICROSECOND DAY_MINUTE DAY_SECOND DEC DECIMAL DECLARE DEFAULT
DELAYED DELETE DELETE_DOMAIN_ID DESC DESCRIBE DETERMINISTIC DISTINCT DISTINCTROW DIV DOUBLE
DO_DOMAIN_IDS DROP DUAL EACH ELSE ELSEIF ENCLOSED ESCAPED EXCEPT EXISTS EXIT EXPLAIN FALSE FETCH
FLOAT FLOAT4 FLOAT8 FOR FORCE FOREIGN FROM FULLTEXT GRANT GROUP HAVING HIGH_PRIORITY
HOUR_MICROSECOND HOUR_MINUTE HOUR_SECOND IF IGNORE IGNORE_DOMAIN_IDS IN INDEX INFILE INNER INOUT
INSENSITIVE INSERT INT INT1 INT2 INT3 INT4 INT8 INTEGER INTERSECT INTERVAL INTO IS ITERATE JOIN
KEY KEYS KILL LEADING LEAVE LEFT LIKE LIMIT LINEAR LINES LOAD LOCALTIME LOCALTIMESTAMP LOCK LONG
LONGBLOB LONGTEXT LOOP LOW_PRIORITY MASTER_DEMOTE_TO_REPLICA MASTER_DEMOTE_TO_SLAVE
MASTER_SSL_VERIFY_SERVER_CERT MATCH MAXVALUE MEDIUMBLOB MEDIUMINT MEDIUMTEXT MIDDLEINT
MINUTE_MICROSECOND MINUTE_SECOND MOD MODIFIES NATURAL NOT NO_WRITE_TO_BINLOG NULL NUMERIC OFFSET
ON OPTIMIZE OPTIONALLY OR ORDER OUT OUTER OUTFILE OVER PAGE_CHECKSUM PARSE_VCOL_EXPR PARTITION
PORTION PRECISION PRIMARY PROCEDURE PURGE RANGE READ READS READ_WRITE REAL RECURSIVE REFERENCES
REF_SYSTEM_ID REGEXP RELEASE RENAME REPEAT REPLACE REQUIRE RESIGNAL RESTRICT RETURN RETURNING
REVOKE RIGHT RLIKE ROWS ROW_NUMBER SCHEMAS SECOND_MICROSECOND SELECT SENSITIVE SEPARATOR SET
SHOW SIGNAL SMALLINT SPATIAL SPECIFIC SQL SQLEXCEPTION SQLSTATE SQLWARNING SQL_BIG_RESULT
SQL_CALC_FOUND_ROWS SQL_SMALL_RESULT SSL STARTING STATS_AUTO_RECALC STATS_PERSISTENT
STATS_SAMPLE_PAGES STRAIGHT_JOIN TABLE TERMINATED THEN TINYBLOB TINYINT TINYTEXT TO TRAILING
TRIGGER TRUE UNDO UNION UNIQUE UNLOCK UNSIGNED UPDATE USAGE USE USING UTC_DATE UTC_TIME
UTC_TIMESTAMP VALUES VARBINARY VARCHAR VARCHARACTER VARYING WHEN WHERE WHILE WITH WRITE XOR
YEAR_MONTH ZEROFILL
""".split())

RESERVED = MYSQL_80 | MYSQL_84_ADDED | MARIADB
"""frozenset: Reserved on at least one supported engine -- upper case."""


def engines(word):
    """The engines `word` is reserved on, for an error message."""
    word = word.upper()
    names = []
    if word in MYSQL_80:
        names.append("MySQL 8.0")
    if word in MYSQL_80 or word in MYSQL_84_ADDED:
        names.append("MySQL 8.4")
    if word in MARIADB:
        names.append("MariaDB")
    return ", ".join(names)
