# tests/test_web_a11y.py

"""
Phone-layout and accessibility checks for every Flask-served page, in a
real browser.

Every GET route of the `web` blueprint (read from the app's `url_map`, so
a page moved to Flask later is covered without touching this file) is
loaded in headless Chromium at 390px (a phone) and 1280px (a laptop), in
the light and the dark color scheme, and must have:

- no axe-core violations of serious or critical impact among the WCAG
  2.0/2.1 A and AA rules;
- no horizontal overflow (the document is never wider than the
  viewport);
- no console errors, uncaught exceptions, failed requests or
  Content-Security-Policy violations;
- a working skip link (the first Tab stop, visible when focused, pointing
  at `<main id="main">`) and an `aria-current="page"` marker.

At 390px the header's Menu is also opened and checked the same way.

The pages run against a small real database generated by `generate.py`
(a few sectors, a standalone system and some phenomena) through the
in-process API transport. A route's URL parameters take sample values
from that database (`SAMPLE_PARAMS` below); a new page with a parameter
name not listed there fails with a message saying to add it. A page that
answers anonymous visitors with a redirect is retried as a logged-in
admin; one that still redirects (a forwarder such as `/search` while the
search page is on CGI) is skipped.

Needs Playwright for Python with Chromium (`pip install playwright` and
`python -m playwright install chromium`, or `PLAYWRIGHT_BROWSERS_PATH`
pointing at an existing install) and the MySQL test server every other
database test uses. Without either, every test here is skipped. Set
`PLANETGEN_A11Y_SCREENSHOTS=<dir>` to also save a screenshot of each page. axe-core
is vendored under `tests/vendor/axe-core/` (MPL-2.0; see its LICENSE)
and injected through the DevTools protocol, so nothing is fetched at
test time and the page's own CSP stays in force.
"""

import os
import random
import threading
import uuid

import pymysql
import pytest

sync_api = pytest.importorskip("playwright.sync_api")

from werkzeug.serving import make_server  # noqa: E402

from api.app import create_app  # noqa: E402
from api.authz import SESSION_COOKIE_NAME  # noqa: E402
from api.config import Config  # noqa: E402
from stellarObjects import _db, adminAuth  # noqa: E402
from stellarObjects._db import MySQLConfig  # noqa: E402

from tests.bughunt_support import mysql_argv, run_cli  # noqa: E402
from tests.conftest import _test_server_kwargs  # noqa: E402

AXE_JS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "vendor", "axe-core", "axe.min.js")

VIEWPORTS = {"phone": {"width": 390, "height": 844}, "desktop": {"width": 1280, "height": 800}}
SCHEMES = ("light", "dark")

SCREENSHOT_DIR = os.environ.get("PLANETGEN_A11Y_SCREENSHOTS")
"""str: When set, a full-page screenshot of every page checked is saved
there as `<endpoint>-<phone|desktop>-<light|dark>.png` (CI uploads them
as an artifact)."""

AXE_TAGS = ["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"]
BLOCKING_IMPACTS = {"serious", "critical"}

# Recorded before any page script runs; CDP-injected, so the page's CSP
# does not block it.
CSP_LISTENER = """
window.__cspViolations = [];
document.addEventListener("securitypolicyviolation", function (e) {
  window.__cspViolations.push(e.violatedDirective + " blocked " + (e.blockedURI || "inline") +
                              " at " + (e.sourceFile || "") + ":" + (e.lineNumber || 0));
});
"""


class _EndpointCatalog:
    """The GET endpoints of the `web` blueprint, read once at collection
    time from an app built with the default config (building the app
    touches no database)."""

    @staticmethod
    def endpoints():
        app = create_app(Config)
        found = {}
        for rule in app.url_map.iter_rules():
            if rule.endpoint.startswith("web.") and "GET" in rule.methods:
                found.setdefault(rule.endpoint, rule)
        return sorted(found)


PAGE_ENDPOINTS = _EndpointCatalog.endpoints()


# --- Browser -------------------------------------------------------------------------

@pytest.fixture(scope="module")
def browser():
    try:
        playwright = sync_api.sync_playwright().start()
    except Exception as exc:  # noqa: BLE001 -- any failure here means "no browser"
        pytest.skip(f"Playwright could not start ({exc})")
    try:
        chromium = playwright.chromium.launch()
    except Exception as exc:  # noqa: BLE001
        playwright.stop()
        pytest.skip(f"No Chromium for Playwright ({str(exc).splitlines()[0]}); run "
                    "`python -m playwright install chromium` or set PLAYWRIGHT_BROWSERS_PATH.")
    try:
        yield chromium
    finally:
        chromium.close()
        playwright.stop()


@pytest.fixture(scope="module")
def axe_source():
    with open(AXE_JS, encoding="utf-8") as handle:
        return handle.read()


# --- Database and server ----------------------------------------------------------------

@pytest.fixture(scope="module")
def site_db(_mysql_server_available):
    """A throwaway database with a small generated galaxy in it, for the
    whole module (generating it once keeps the run short)."""
    kwargs = _test_server_kwargs()
    name = f"planetgen_a11y_{uuid.uuid4().hex[:12]}"
    admin_conn = pymysql.connect(**kwargs)
    try:
        with admin_conn.cursor() as cur:
            cur.execute(f"CREATE DATABASE `{name}`")
        admin_conn.commit()
    finally:
        admin_conn.close()
    config = MySQLConfig(database=name, **kwargs)
    try:
        state = random.getstate()
        random.seed(20260924)
        try:
            target = mysql_argv(config)
            run_cli("plan", ["--workers", "1", "--quiet"] + target)
            run_cli("galaxy", ["--shell", "0", "--num-systems", "4", "+planets", "--yes", "--quiet"] + target)
            run_cli("system", ["--quiet"] + target)
            for kind in ("nebula", "black-hole", "rogue-planet", "asteroid-field"):
                run_cli("phenomenon", ["--type", kind, "--quiet"] + target)
        finally:
            random.setstate(state)
        yield config
    finally:
        _db.close_pool(config)
        admin_conn = pymysql.connect(**kwargs)
        try:
            with admin_conn.cursor() as cur:
                cur.execute(f"DROP DATABASE IF EXISTS `{name}`")
            admin_conn.commit()
        finally:
            admin_conn.close()


@pytest.fixture(scope="module")
def site_app(site_db):
    class SiteConfig(Config):
        MYSQL_CONFIG = site_db
        WRITE_MYSQL_CONFIG = site_db
        CONTROL_MYSQL_CONFIG = site_db
        WEB_DATABASE = ""
        SESSION_COOKIE_SECURE = False
        SECRET_KEY = "a11y-test-secret"

    app = create_app(SiteConfig)
    app.testing = True
    return app


@pytest.fixture(scope="module")
def admin_token(site_db):
    """A logged-in admin session (credentials already changed, so no
    page forces the change-credentials form)."""
    adminAuth.bootstrap_control_schema(site_db)
    conn = _db.get_control_connection(site_db)
    try:
        conn.execute("UPDATE admin_users SET must_change_credentials = 0")
        conn.commit()
        admin_id = conn.execute("SELECT id FROM admin_users ORDER BY id LIMIT 1").fetchone()["id"]
        return adminAuth.create_session(conn, admin_id)
    finally:
        conn.close()


@pytest.fixture(scope="module")
def base_url(site_app):
    server = make_server("127.0.0.1", 0, site_app, threaded=True)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        yield f"http://127.0.0.1:{server.server_port}"
    finally:
        server.shutdown()
        thread.join(timeout=10)


# --- Sample URL parameters ------------------------------------------------------------

@pytest.fixture(scope="module")
def sample_params(site_app):
    """
    A value for every URL parameter a page route may take, drawn from the
    generated database through the JSON API. Add an entry here when a
    new page introduces a parameter name not listed.
    """
    client = site_app.test_client()

    def items(path):
        resp = client.get(path)
        assert resp.status_code == 200, (path, resp.status_code)
        return resp.get_json()["items"]

    sectors = [s for s in items("/api/sectors?limit=100") if s["system_count"]]
    sector = sectors[0]
    systems = items(f"/api/systems?sector_id={sector['id']}&limit=100")
    phenomena = items("/api/phenomena?limit=100")
    phenomenon = phenomena[0]
    return {
        "sector_id": sector["id"],
        "system_id": systems[0]["id"],
        "from_id": systems[0]["id"],
        "to_id": systems[-1]["id"],
        "phenomenon_type": phenomenon["type"],
        "phenomenon_id": phenomenon["id"],
        "quadrant": "I",
        "page": 1,
    }


def _page_url(app, endpoint, samples):
    rule = next(r for r in app.url_map.iter_rules() if r.endpoint == endpoint)
    missing = sorted(arg for arg in rule.arguments if arg not in samples)
    if missing:
        pytest.fail(f"{endpoint} ({rule.rule}) takes {', '.join(missing)}: add a sample value "
                    f"to sample_params in {os.path.basename(__file__)}")
    with app.test_request_context("/"):
        from flask import url_for
        return url_for(endpoint, **{arg: samples[arg] for arg in rule.arguments})


@pytest.fixture(scope="module")
def page_targets(site_app, sample_params, admin_token):
    """endpoint -> (path, needs_admin) or (None, reason to skip)."""
    targets = {}
    anonymous = site_app.test_client()
    admin = site_app.test_client()
    admin.set_cookie(SESSION_COOKIE_NAME, admin_token)
    for endpoint in PAGE_ENDPOINTS:
        path = _page_url(site_app, endpoint, sample_params)
        status = anonymous.get(path).status_code
        if status == 200:
            targets[endpoint] = (path, False)
            continue
        admin_status = admin.get(path).status_code
        if admin_status == 200:
            targets[endpoint] = (path, True)
        elif 300 <= status < 400 and 300 <= admin_status < 400:
            targets[endpoint] = (None, f"{path} only redirects")
        else:
            pytest.fail(f"{endpoint}: GET {path} answered {status} (anonymous) / "
                        f"{admin_status} (admin) with the sample database")
    return targets


# --- The checks -----------------------------------------------------------------------

def _axe_blocking(page, axe_source, context=None):
    if not page.evaluate("typeof window.axe !== 'undefined'"):
        page.evaluate(axe_source)
    result = page.evaluate(
        """([context, tags]) => axe.run(context ? document.querySelector(context) : document,
                                        {runOnly: {type: "tag", values: tags}, resultTypes: ["violations"]})""",
        [context, AXE_TAGS],
    )
    problems = []
    for violation in result["violations"]:
        if violation["impact"] not in BLOCKING_IMPACTS:
            continue
        nodes = []
        for node in violation["nodes"][:5]:
            checks = node.get("any") or node.get("all") or node.get("none") or [{}]
            nodes.append(f"{' '.join(map(str, node['target']))}: {checks[0].get('message', '')}")
        problems.append(f"axe {violation['id']} ({violation['impact']}): {violation['help']}\n      "
                        + "\n      ".join(nodes))
    return problems


def _overflow(page):
    widths = page.evaluate(
        "({doc: document.documentElement.scrollWidth, body: document.body.scrollWidth,"
        " view: document.documentElement.clientWidth})"
    )
    if max(widths["doc"], widths["body"]) > widths["view"]:
        wide = page.evaluate(
            """() => {
                const view = document.documentElement.clientWidth, out = [];
                for (const el of document.querySelectorAll("body *")) {
                    const r = el.getBoundingClientRect();
                    let clipped = false;
                    for (let up = el.parentElement; up && up !== document.body; up = up.parentElement) {
                        if (getComputedStyle(up).overflowX !== "visible") { clipped = true; break; }
                    }
                    if (!clipped && r.right > view + 1 && getComputedStyle(el).position !== "fixed") {
                        out.push(el.tagName.toLowerCase() + (el.id ? "#" + el.id : "") +
                                 (el.className && typeof el.className === "string" ? "." + el.className.trim().split(/\\s+/).join(".") : "") +
                                 " right=" + Math.round(r.right));
                        if (out.length >= 5) break;
                    }
                }
                return out;
            }"""
        )
        return [f"horizontal overflow: scrollWidth {max(widths['doc'], widths['body'])} > "
                f"viewport {widths['view']} ({wide})"]
    return []


@pytest.mark.parametrize("scheme", SCHEMES)
@pytest.mark.parametrize("viewport", sorted(VIEWPORTS))
@pytest.mark.parametrize("endpoint", PAGE_ENDPOINTS)
def test_page_is_accessible_and_fits(browser, axe_source, base_url, page_targets, admin_token,
                                     endpoint, viewport, scheme):
    path, needs_admin = page_targets[endpoint]
    if path is None:
        pytest.skip(needs_admin)

    context = browser.new_context(viewport=VIEWPORTS[viewport], color_scheme=scheme,
                                  device_scale_factor=1, reduced_motion="reduce")
    if needs_admin:
        context.add_cookies([{"name": SESSION_COOKIE_NAME, "value": admin_token, "url": base_url}])
    context.add_init_script(CSP_LISTENER)
    page = context.new_page()
    problems = []
    page.on("console", lambda msg: msg.type == "error" and problems.append(f"console error: {msg.text}"))
    page.on("pageerror", lambda exc: problems.append(f"uncaught exception: {exc}"))
    page.on("requestfailed", lambda req: problems.append(f"request failed: {req.url} ({req.failure})"))
    page.on("response", lambda resp: resp.status >= 400 and problems.append(
        f"HTTP {resp.status}: {resp.url}"))
    try:
        response = page.goto(base_url + path, wait_until="load")
        assert response.status == 200, f"{path} answered {response.status}"
        page.wait_for_timeout(100)

        if SCREENSHOT_DIR:
            os.makedirs(SCREENSHOT_DIR, exist_ok=True)
            page.screenshot(path=os.path.join(SCREENSHOT_DIR, f"{endpoint[4:]}-{viewport}-{scheme}.png"),
                            full_page=True)

        problems += _overflow(page)
        problems += _axe_blocking(page, axe_source)

        # Skip link: the first Tab stop, visible once focused, pointing at <main id="main">.
        page.keyboard.press("Tab")
        skip = page.evaluate(
            """() => {
                const a = document.activeElement, main = document.getElementById("main");
                const r = a.getBoundingClientRect();
                return {cls: a.className, href: a.getAttribute("href"),
                        main: !!main && main.tagName === "MAIN",
                        visible: r.width > 0 && r.height > 0 && r.top >= 0 && r.left >= 0 &&
                                 r.right <= document.documentElement.clientWidth};
            }"""
        )
        if not (skip["cls"] == "skip-link" and skip["href"] == "#main" and skip["main"] and skip["visible"]):
            problems.append(f"skip link is not the first, visible Tab stop into <main id=main>: {skip}")

        if page.locator('[aria-current="page"]').count() == 0:
            problems.append('no aria-current="page" anywhere on the page')

        if viewport == "phone" and page.locator("details.site-menu > summary").is_visible():
            page.locator("details.site-menu > summary").click()
            page.wait_for_timeout(50)
            problems += [f"(menu open) {p}" for p in _overflow(page)]
            problems += [f"(menu open) {p}" for p in _axe_blocking(page, axe_source, "header")]

        problems += [f"CSP violation: {v}" for v in page.evaluate("window.__cspViolations || []")]
    finally:
        context.close()

    assert not problems, f"{path} at {viewport}/{scheme}:\n  " + "\n  ".join(problems)


@pytest.mark.parametrize("scheme", SCHEMES)
def test_error_page_is_accessible(browser, axe_source, base_url, scheme):
    """The HTML 404 page (every missing page and bad id lands on it)."""
    for viewport in VIEWPORTS.values():
        context = browser.new_context(viewport=viewport, color_scheme=scheme, device_scale_factor=1)
        context.add_init_script(CSP_LISTENER)
        page = context.new_page()
        try:
            response = page.goto(base_url + "/no/such/page", wait_until="load")
            assert response.status == 404
            problems = _overflow(page) + _axe_blocking(page, axe_source)
            problems += [f"CSP violation: {v}" for v in page.evaluate("window.__cspViolations || []")]
            assert page.locator('a.skip-link[href="#main"]').count() == 1
        finally:
            context.close()
        assert not problems, f"404 page at {viewport['width']}px/{scheme}:\n  " + "\n  ".join(problems)
