"""
Exotic stellar phenomena regression tests
==========================================

Covers the seven phenomena generated by `phenomenonGen.py`'s separate,
rarer generation mode -- `compactRemnant.BlackHole`/`NeutronStar`,
`nebulaData.Nebula`, `supernovaRemnantData.SupernovaRemnant`,
`roguePlanetData.RoguePlanet`/`InterstellarComet`,
`asteroidFieldData.AsteroidField` -- plus the
`StarSystem(compact_remnant=...)` integration point the two compact
remnants anchor through, and the galactic-orbital-motion fields every
standalone phenomenon shares (see `nebulaData.Nebula`'s docstring).

Generation-sanity/serialization/rendering tests need no database and always
run. The persistence tests at the bottom take the `mysql_config` fixture
(see `conftest.py`) and are skipped, not failed, when no MySQL test server
is configured/reachable.

Run with: pytest src/tests/test_phenomena.py
"""

import math

import pytest

from stellarObjects import _db, physical_constants, program_constants
from stellarObjects.asteroidFieldData import AsteroidField
from stellarObjects.compactRemnant import BlackHole, CompactRemnant, NeutronStar
from stellarObjects.config import SystemConfig
from stellarObjects.nebulaData import Nebula
from stellarObjects.roguePlanetData import InterstellarComet, RoguePlanet
from stellarObjects.supernovaRemnantData import SupernovaRemnant
from stellarObjects.systemData import StarSystem

TRIALS = 8

STANDALONE_PHENOMENON_CLASSES = [Nebula, SupernovaRemnant, RoguePlanet, InterstellarComet, AsteroidField]
"""list: Every phenomenon that is always standalone (never anchors a
StarSystem) -- shares the "== Name (Type) ==" header convention and the
galactic-orbital-motion fields, unlike BlackHole/NeutronStar (Star
subclasses, see test_compact_remnant_paragraph_list_renders_data_block_with_no_section_header)."""


def make_config(**overrides):
    cfg = SystemConfig()
    for attr, value in overrides.items():
        setattr(cfg, attr, value)
    return cfg


# ---------------------------------------------------------------------------
# Generation sanity -- values stay within their program_constants ranges.
# ---------------------------------------------------------------------------

def test_black_hole_mass_and_spin_within_configured_ranges():
    for _ in range(TRIALS):
        bh = BlackHole(make_config())
        assert (
            program_constants.BLACK_HOLE_MASS_RANGE_SOLAR[0] <= bh.mass_solar <= program_constants.BLACK_HOLE_MASS_RANGE_SOLAR[1]
            or program_constants.BLACK_HOLE_INTERMEDIATE_MASS_RANGE_SOLAR[0] <= bh.mass_solar <= program_constants.BLACK_HOLE_INTERMEDIATE_MASS_RANGE_SOLAR[1]
        )
        assert program_constants.BLACK_HOLE_SPIN_RANGE[0] <= bh.spin <= program_constants.BLACK_HOLE_SPIN_RANGE[1]
        assert bh.event_horizon_radius_km > 0
        assert bh.radius == bh.event_horizon_radius_km
        assert bh.yerkes_class == "BH"
        assert bh.lifespan == float('inf')
        if not bh.has_accretion_disk:
            assert bh.luminosity == 0.0
            assert bh.habitable_zone == (0.0, 0.0)


def test_black_hole_schwarzschild_radius_matches_known_value():
    # A 10 Msun black hole's Schwarzschild radius is a commonly-cited
    # reference value (~29.5 km) -- verify the formula directly rather
    # than only checking it falls in a range.
    cfg = make_config()
    bh = object.__new__(BlackHole)
    bh.mass = 10 * physical_constants.SOLAR_MASS_TO_KG
    schwarzschild_radius_m = 2 * physical_constants.G * bh.mass / physical_constants.SPEED_OF_LIGHT_M_S ** 2
    assert schwarzschild_radius_m / 1000 == pytest.approx(29.5, abs=0.5)


def test_neutron_star_mass_radius_and_temperature_within_configured_ranges():
    for _ in range(TRIALS):
        ns = NeutronStar(make_config())
        assert program_constants.NEUTRON_STAR_MASS_RANGE_SOLAR[0] <= ns.mass_solar <= program_constants.NEUTRON_STAR_MASS_RANGE_SOLAR[1]
        assert program_constants.NEUTRON_STAR_RADIUS_RANGE_KM[0] <= ns.radius <= program_constants.NEUTRON_STAR_RADIUS_RANGE_KM[1]
        assert program_constants.NEUTRON_STAR_SURFACE_TEMPERATURE_RANGE_K[0] <= ns.surface_temperature_k <= program_constants.NEUTRON_STAR_SURFACE_TEMPERATURE_RANGE_K[1]
        assert ns.pulsar_type in ("young", "millisecond", "non-pulsing")
        assert ns.yerkes_class == "NS"
        assert ns.lifespan == float('inf')
        assert ns.luminosity > 0  # nonzero even at the coolest end -- see NeutronStar.__init__


def test_compact_remnants_are_star_subclasses():
    assert issubclass(BlackHole, CompactRemnant)
    assert issubclass(NeutronStar, CompactRemnant)
    from stellarObjects.starData import Star
    assert issubclass(CompactRemnant, Star)


def test_nebula_type_and_radius_within_configured_ranges():
    for _ in range(TRIALS):
        nebula = Nebula(make_config())
        assert nebula.nebula_type in program_constants.NEBULA_TYPES
        radius_range = program_constants.NEBULA_TYPES[nebula.nebula_type]["radius_range_ly"]
        assert radius_range[0] <= nebula.radius_ly <= radius_range[1]


def test_supernova_remnant_morphology_and_sedov_taylor_radius():
    for _ in range(TRIALS):
        remnant = SupernovaRemnant(make_config())
        assert remnant.morphology in program_constants.SUPERNOVA_REMNANT_MORPHOLOGIES
        assert program_constants.SUPERNOVA_REMNANT_AGE_RANGE_YEARS[0] <= remnant.age_years <= program_constants.SUPERNOVA_REMNANT_AGE_RANGE_YEARS[1]
        expected_radius = (
            program_constants.SEDOV_TAYLOR_RADIUS_COEFFICIENT_LY
            * (remnant.age_years ** program_constants.SEDOV_TAYLOR_TIME_EXPONENT)
        )
        assert remnant.radius_ly == pytest.approx(expected_radius)
        assert remnant.progenitor_type in ("Type Ia", "core-collapse")
        if remnant.progenitor_type == "Type Ia":
            # A Type Ia progenitor is thermonuclearly disrupted entirely --
            # nothing is ever left behind.
            assert remnant.compact_remnant is None
        if remnant.compact_remnant is not None:
            assert isinstance(remnant.compact_remnant, (BlackHole, NeutronStar))


def test_rogue_planet_mass_and_type_within_configured_ranges():
    for _ in range(TRIALS):
        planet = RoguePlanet(make_config())
        mass_jupiter = planet.mass_kg / physical_constants.JUPITER_MASS_TO_KG
        assert program_constants.ROGUE_PLANET_MASS_RANGE_JUPITER[0] <= mass_jupiter <= program_constants.ROGUE_PLANET_MASS_RANGE_JUPITER[1]
        assert planet.planet_type in ('t', 'g')
        if planet.planet_type == 'g':
            assert mass_jupiter >= program_constants.ROGUE_PLANET_GAS_GIANT_MASS_THRESHOLD_JUPITER
        else:
            assert mass_jupiter < program_constants.ROGUE_PLANET_GAS_GIANT_MASS_THRESHOLD_JUPITER
        assert planet.radius_km > 0
        assert planet.mass_kg > 0


def test_interstellar_comet_within_configured_ranges():
    for _ in range(TRIALS):
        comet = InterstellarComet(make_config())
        assert program_constants.INTERSTELLAR_COMET_NUCLEUS_DIAMETER_RANGE_KM[0] <= comet.nucleus_diameter_km <= program_constants.INTERSTELLAR_COMET_NUCLEUS_DIAMETER_RANGE_KM[1]
        assert program_constants.INTERSTELLAR_OBJECT_SPEED_KMS_RANGE[0] <= comet.velocity_kms <= program_constants.INTERSTELLAR_OBJECT_SPEED_KMS_RANGE[1]
        assert 0 < len(comet.composition) <= 3
        assert all(component in program_constants.COMET_COMPOSITION for component in comet.composition)


def test_asteroid_field_within_configured_ranges():
    for _ in range(TRIALS):
        field = AsteroidField(make_config())
        assert program_constants.ASTEROID_FIELD_RADIUS_RANGE_LY[0] <= field.radius_ly <= program_constants.ASTEROID_FIELD_RADIUS_RANGE_LY[1]
        assert field.density in ("dense", "sparse", "typical")
        assert 0 < len(field.composition) <= 4
        for component, concentration in field.composition:
            assert component in program_constants.ASTEROID_COMPONENTS
            assert concentration in ("high", "moderate", "small", "trace")


@pytest.mark.parametrize("cls", [BlackHole, NeutronStar] + STANDALONE_PHENOMENON_CLASSES)
def test_galactic_orbital_fields_are_well_formed(cls):
    # Every phenomenon (compact remnant or standalone) shares this
    # quartet -- see nebulaData.Nebula's `galactic_orbital_*` docstring
    # and utils.generate_galactic_orbit_fields.
    for _ in range(TRIALS):
        obj = cls(make_config())
        assert math.isfinite(obj.galactic_orbital_speed_kms) and obj.galactic_orbital_speed_kms > 0
        assert math.isfinite(obj.galactic_orbital_period_gy) and obj.galactic_orbital_period_gy > 0
        assert math.isfinite(obj.galactic_orbital_phase_deg) and 0 <= obj.galactic_orbital_phase_deg < 360
        assert math.isfinite(obj.galactic_min_update_interval_years) and obj.galactic_min_update_interval_years > 0


# ---------------------------------------------------------------------------
# Serialization round-trips (to_dict/from_dict).
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("cls", [BlackHole, NeutronStar] + STANDALONE_PHENOMENON_CLASSES)
def test_to_dict_from_dict_round_trips_render_identically(cls):
    cfg = make_config()
    obj = cls(cfg)
    reloaded = cls.from_dict(obj.to_dict(), cfg)
    assert str(reloaded) == str(obj)
    assert reloaded.to_dict() == obj.to_dict()


def test_supernova_remnant_round_trip_preserves_embedded_compact_remnant():
    cfg = make_config()
    # Force a core-collapse progenitor with a visible remnant by retrying
    # generation until one comes out -- these are probabilistic, not
    # guaranteed on a single roll.
    for _ in range(50):
        remnant = SupernovaRemnant(cfg)
        if remnant.compact_remnant is not None:
            break
    else:
        pytest.fail("could not generate a supernova remnant with a visible compact remnant")

    reloaded = SupernovaRemnant.from_dict(remnant.to_dict(), cfg)
    assert type(reloaded.compact_remnant) is type(remnant.compact_remnant)
    assert reloaded.compact_remnant.name == remnant.compact_remnant.name
    assert str(reloaded) == str(remnant)


# ---------------------------------------------------------------------------
# Paragraph rendering -- non-empty, correct header convention under both
# MARKDOWN states (mirrors AsteroidBelt/Star's own '##'/'==' convention).
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("cls", STANDALONE_PHENOMENON_CLASSES)
@pytest.mark.parametrize("markdown", [True, False])
def test_standalone_phenomenon_paragraph_list_renders_section_header(cls, markdown):
    # These five are always standalone (never anchor a StarSystem), so
    # they follow AsteroidBelt's own "## .. ##"/"== .. ==" section-header
    # convention -- unlike BlackHole/NeutronStar below, which are Star
    # subclasses and never add their own header (see that test's docstring).
    cfg = make_config(MARKDOWN=markdown)
    obj = cls(cfg)
    paragraphs = obj.to_paragraph_list()
    assert paragraphs
    assert all(isinstance(p, str) and p for p in paragraphs)
    header = paragraphs[0]
    if markdown:
        assert header.startswith("##")
        assert not header.endswith("==")
    else:
        assert header.startswith("==")
        assert header.endswith("==")
    assert str(obj) == "\n\n".join(paragraphs)


@pytest.mark.parametrize("cls", [BlackHole, NeutronStar])
@pytest.mark.parametrize("markdown", [True, False])
def test_compact_remnant_paragraph_list_renders_data_block_with_no_section_header(cls, markdown):
    # BlackHole/NeutronStar are Star subclasses (see compactRemnant.py's
    # module docstring) and follow Star.to_paragraph_list's own
    # convention: no self-added "== Name ==" section header (StarSystem's
    # own __str__ adds a single top-level "= Name =" header when one of
    # these anchors a full system -- adding a second header here would
    # duplicate it).
    cfg = make_config(MARKDOWN=markdown)
    obj = cls(cfg)
    paragraphs = obj.to_paragraph_list()
    assert paragraphs
    assert all(isinstance(p, str) and p for p in paragraphs)
    data_block = paragraphs[0]
    if markdown:
        assert data_block.startswith("| Property | Value |")
    else:
        assert data_block.startswith("{{")
        assert data_block.endswith("}}")
    assert str(obj) == "\n\n".join(paragraphs)


# ---------------------------------------------------------------------------
# StarSystem(compact_remnant=...) integration.
# ---------------------------------------------------------------------------

def test_star_system_anchored_by_black_hole_skips_binary_generation():
    cfg = make_config(BINARY_SYSTEM=True)  # would force a binary for a normal Star
    bh = BlackHole(cfg)
    system = StarSystem(system_config=cfg, compact_remnant=bh)
    assert system.star is bh
    assert system.primary_star is bh
    assert system.binary_type is None
    assert system.wide_binary is None
    assert system.stars == [bh]


def test_star_system_anchored_by_neutron_star_can_force_planets():
    cfg = make_config(NUM_ORBITS=2)
    ns = NeutronStar(cfg)
    system = StarSystem(system_config=cfg, compact_remnant=ns)
    assert system.star is ns
    assert system.planet_count + system.belt_count == 2
    # A dark remnant's zero/near-zero luminosity means no real habitable
    # zone -- adjust_age_for_planets and rendering must not crash even
    # though every placed body is far outside any thermal comfort zone.
    assert str(system)


def test_star_system_anchored_by_black_hole_defaults_to_no_planets():
    # Disk-physics-driven generation (StarSystem._estimate_max_objects_from_disk_physics)
    # is snow-line-driven, which naturally collapses to zero for a
    # zero-luminosity remnant -- the real-world rarity of confirmed
    # planets around black holes falls out of the existing physics model
    # rather than needing a special case.
    cfg = make_config()
    bh = BlackHole(cfg)
    if bh.has_accretion_disk:
        pytest.skip("this trial's black hole has a nonzero-luminosity accretion disk")
    system = StarSystem(system_config=cfg, compact_remnant=bh)
    assert system.planet_count == 0
    assert system.belt_count == 0


# ---------------------------------------------------------------------------
# Database persistence (insert/load round trips) -- skipped without a
# reachable MySQL test server (see conftest.py's mysql_config fixture).
# ---------------------------------------------------------------------------

def test_insert_and_reload_standalone_black_hole(mysql_config):
    cfg = make_config()
    bh = BlackHole(cfg)

    conn = _db.get_connection(mysql_config)
    try:
        with conn:
            black_hole_id = _db.insert_black_hole(conn, bh)
        row = conn.execute("SELECT * FROM black_holes WHERE id = ?", (black_hole_id,)).fetchone()
    finally:
        conn.close()

    assert row["star_id"] is None
    assert row["name"] == bh.name
    assert row["mass_solar"] == pytest.approx(bh.mass_solar)
    assert row["event_horizon_radius_km"] == pytest.approx(bh.event_horizon_radius_km)
    assert bool(row["has_accretion_disk"]) == bh.has_accretion_disk


def test_insert_and_reload_standalone_neutron_star(mysql_config):
    cfg = make_config()
    ns = NeutronStar(cfg)

    conn = _db.get_connection(mysql_config)
    try:
        with conn:
            neutron_star_id = _db.insert_neutron_star(conn, ns)
        row = conn.execute("SELECT * FROM neutron_stars WHERE id = ?", (neutron_star_id,)).fetchone()
    finally:
        conn.close()

    assert row["star_id"] is None
    assert row["pulsar_type"] == ns.pulsar_type
    assert row["mass_solar"] == pytest.approx(ns.mass_solar)


def test_insert_and_reload_nebula(mysql_config):
    cfg = make_config()
    nebula = Nebula(cfg)

    conn = _db.get_connection(mysql_config)
    try:
        with conn:
            nebula_id = _db.insert_nebula(conn, nebula)
        row = conn.execute("SELECT * FROM nebulae WHERE id = ?", (nebula_id,)).fetchone()
    finally:
        conn.close()

    assert row["nebula_type"] == nebula.nebula_type
    assert row["radius_ly"] == pytest.approx(nebula.radius_ly)


def test_insert_and_reload_supernova_remnant_with_embedded_compact_remnant(mysql_config):
    cfg = make_config()
    for _ in range(50):
        remnant = SupernovaRemnant(cfg)
        if remnant.compact_remnant is not None:
            break
    else:
        pytest.fail("could not generate a supernova remnant with a visible compact remnant")

    conn = _db.get_connection(mysql_config)
    try:
        with conn:
            remnant_id = _db.insert_supernova_remnant(conn, remnant)
        row = conn.execute("SELECT * FROM supernova_remnants WHERE id = ?", (remnant_id,)).fetchone()
    finally:
        conn.close()

    assert row["morphology"] == remnant.morphology
    if isinstance(remnant.compact_remnant, BlackHole):
        assert row["compact_remnant_kind"] == "black_hole"
        assert row["compact_remnant_black_hole_id"] is not None
        assert row["compact_remnant_neutron_star_id"] is None
    else:
        assert row["compact_remnant_kind"] == "neutron_star"
        assert row["compact_remnant_neutron_star_id"] is not None
        assert row["compact_remnant_black_hole_id"] is None


def test_insert_and_reload_rogue_planet(mysql_config):
    cfg = make_config()
    planet = RoguePlanet(cfg)

    conn = _db.get_connection(mysql_config)
    try:
        with conn:
            planet_id = _db.insert_rogue_planet(conn, planet)
        row = conn.execute("SELECT * FROM rogue_planets WHERE id = ?", (planet_id,)).fetchone()
    finally:
        conn.close()

    assert row["planet_type"] == planet.planet_type
    assert row["mass_kg"] == pytest.approx(planet.mass_kg)


def test_insert_and_reload_interstellar_comet_with_composition(mysql_config):
    cfg = make_config()
    comet = InterstellarComet(cfg)

    conn = _db.get_connection(mysql_config)
    try:
        with conn:
            comet_id = _db.insert_interstellar_comet(conn, comet)
        row = conn.execute("SELECT * FROM interstellar_comets WHERE id = ?", (comet_id,)).fetchone()
        composition_rows = conn.execute(
            "SELECT component FROM interstellar_comet_composition WHERE comet_id = ? ORDER BY position", (comet_id,)
        ).fetchall()
    finally:
        conn.close()

    assert row["nucleus_diameter_km"] == pytest.approx(comet.nucleus_diameter_km)
    assert [r["component"] for r in composition_rows] == comet.composition


def test_insert_and_reload_asteroid_field_with_composition(mysql_config):
    cfg = make_config()
    field = AsteroidField(cfg)

    conn = _db.get_connection(mysql_config)
    try:
        with conn:
            field_id = _db.insert_asteroid_field(conn, field)
        row = conn.execute("SELECT * FROM asteroid_fields WHERE id = ?", (field_id,)).fetchone()
        composition_rows = conn.execute(
            "SELECT component, concentration FROM asteroid_field_composition WHERE field_id = ? ORDER BY position",
            (field_id,),
        ).fetchall()
    finally:
        conn.close()

    assert row["density"] == field.density
    assert row["radius_ly"] == pytest.approx(field.radius_ly)
    assert row["galactic_orbital_phase_deg"] == pytest.approx(field.galactic_orbital_phase_deg)
    assert [(r["component"], r["concentration"]) for r in composition_rows] == field.composition


def test_star_system_anchored_by_black_hole_persists_satellite_row(mysql_config):
    cfg = make_config(NUM_ORBITS=1)
    bh = BlackHole(cfg)
    system = StarSystem(system_config=cfg, compact_remnant=bh)

    conn = _db.get_connection(mysql_config)
    try:
        with conn:
            system_id = _db.insert_star_system(conn, system, cfg)
        star_row = conn.execute(
            "SELECT * FROM stars WHERE star_system_id = ? AND role = 'single'", (system_id,)
        ).fetchone()
        black_hole_row = conn.execute(
            "SELECT * FROM black_holes WHERE star_id = ?", (star_row["id"],)
        ).fetchone()
    finally:
        conn.close()

    assert star_row["yerkes_class"] == "BH"
    assert star_row["galactic_orbital_phase_deg"] is not None
    assert black_hole_row is not None
    assert black_hole_row["name"] == bh.name
    # An anchored remnant's motion lives on its stars row above, not
    # duplicated here -- see insert_black_hole's own docstring.
    assert black_hole_row["galactic_orbital_phase_deg"] is None


@pytest.mark.parametrize("cls", [BlackHole, NeutronStar])
def test_load_star_system_reconstructs_anchored_compact_remnant(cls, mysql_config):
    # Regression test: load_star_system's single-star branch used to
    # unconditionally call Star.from_dict, silently reconstructing an
    # anchored compact remnant as a plain Star (losing its extra fields
    # and remnant-specific rendering) rather than dispatching on the
    # black_holes/neutron_stars satellite row. See _db._load_single_star.
    cfg = make_config()
    remnant = cls(cfg)
    system = StarSystem(system_config=cfg, compact_remnant=remnant)

    conn = _db.get_connection(mysql_config)
    try:
        with conn:
            system_id = _db.insert_star_system(conn, system, cfg)
        reloaded = _db.load_star_system(conn, system_id)
    finally:
        conn.close()

    assert isinstance(reloaded.star, cls)
    assert reloaded.star.name == remnant.name
    assert reloaded.star.type == remnant.type
    assert reloaded.star.yerkes_class == remnant.yerkes_class
    assert reloaded.star.mass_solar == pytest.approx(remnant.mass_solar)
    # Not exact string equality -- a DOUBLE round-trip through MySQL can
    # shift a formatted value's last displayed digit (e.g. temperature
    # rounding right at a .5 boundary), which is expected float noise, not
    # a reconstruction bug. The "Black Hole Data"/"Neutron Star Data"
    # header proves the remnant-specific to_paragraph_list() ran at all
    # (a plain Star would render "Star Data" instead).
    label = "Black Hole Data" if cls is BlackHole else "Neutron Star Data"
    assert label in str(reloaded.star)


def test_save_phenomenon_dispatches_by_type(mysql_config):
    cfg = make_config()
    comet = InterstellarComet(cfg)
    comet_id = _db.save_phenomenon(comet, cfg, "comet", config=mysql_config)

    conn = _db.get_connection(mysql_config)
    try:
        row = conn.execute("SELECT * FROM interstellar_comets WHERE id = ?", (comet_id,)).fetchone()
    finally:
        conn.close()
    assert row["name"] == comet.name
