#!/usr/bin/env python
# galaxyGen.py

"""
Galaxy-Scale Sector Generation
================================

Generates and persists many sectors as one galaxy, per
`docs/design/galaxy-coordinate-system.md` (the shell/Fibonacci-sphere
radial tiling scheme, section 3) and `docs/TODO.md`'s Phase 4. This
script does not generate systems or sectors itself -- it calls straight
into `sectorGen.py`'s own `generate_sector()` (which in turn reuses
`build_sector_configs()`/`systemGen.build_system_config`) for the actual
per-sector generation, and into `stellarObjects._db.save_sector` for
persistence, so a sector generated here and one generated by
`sectorGen.py` directly are built by the exact same code path -- the only
difference is that this script also supplies a real galaxy-frame position
(threaded down to `Star.calculate_system_perimeter` as
`galactic_center_dist_ly`, replacing the fixed
`physical_constants.GALACTIC_CENTER_DISTANCE_LY` constant every
standalone-generated system otherwise uses) and records that position in
`sectors.center_x/y/z_pc`/`galactic_radius_pc`/`shell_index`/
`shell_slot_index`/`vertices_pc` (this sector's own neighbor-relaxed cube
corners -- see `stellarObjects/sectorGeometry.relax_vertices`).

Two generation modes, both reducing to one call of
`stellarObjects.galaxyGeometry.enumerate_sectors_within_radius` (see
`docs/design/galaxy-coordinate-system.md` section 8 for the geometry this
implements and its Big-O):

- **Batch mode** (`--shell K`): generates every not-yet-generated sector
  slot in radial shell `K`. Shell sector counts grow quadratically (see
  the design doc's section 3 table -- shell 100 alone holds ~127,000
  slots, the outermost shell of a 15,000 pc galaxy ~227 million) --
  `--limit N` generates only the first `N` not-yet-generated slots
  instead of the whole shell, and a shell above
  `LARGE_SHELL_WARNING_THRESHOLD` slots requires either `--limit` or
  `--yes` before this non-interactive script will proceed, so a bare
  `--shell 4253` can't silently attempt hundreds of millions of rows.
- **Local-neighborhood mode** (`--center-sector <id> --radius-pc R`):
  generates every not-yet-generated sector slot within `R` parsecs of an
  *already placed* sector's own stored center -- a local starmap radiating
  outward from a point of interest, without requiring that sector's whole
  enclosing shell to exist first. `<id>` must already have a galaxy
  position (i.e. was itself generated via this script, or via `--shell`)
  -- a sector generated by `sectorGen.py`'s own standalone CLI has no
  galaxy position to search a neighborhood around.

Either mode skips any candidate slot a sector already occupies
(`stellarObjects._db.get_occupied_shell_slots`) rather than regenerating
or erroring on it, so re-running this script over a partially-generated
shell or neighborhood only fills in what's missing.
"""

import argparse
import logging
import os
import random
import secrets
import sys

# stellarObjects lives at src/stellarObjects (src layout) -- add src/ to the
# import path so this keeps working without requiring `pip install .`
# first, matching sectorGen.py/systemGen.py's own fallback.
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))

import sectorGen
from stellarObjects import _db, program_constants
from stellarObjects._version import VersionAction, version_banner
from stellarObjects.galaxyGeometry import (
    enumerate_sectors_within_radius, galactic_radius_pc, sector_position_pc, shell_sector_count,
)
from stellarObjects.sectorGeometry import relax_vertices
from stellarObjects.utils import ly_to_pc, pc_to_ly

# Suppress transformers warnings
logging.getLogger("transformers").setLevel(logging.ERROR)

LARGE_SHELL_WARNING_THRESHOLD = 2000
"""int: `--shell K` requires `--limit` or `--yes` when shell `K` holds
more sector slots than this -- see `shell_sector_count`. Chosen so a
handful of inner shells (through roughly shell 20, ~5,400 slots -- close
to but slightly above this threshold at the boundary, so the check is
deliberately conservative) can be generated without an extra flag, while
anything large enough to take a real, unbounded amount of time and disk
space requires an explicit, deliberate choice."""


def process_args():
    """
    Parses command-line arguments for `galaxyGen.py`.

    Every per-system generation-tuning option `sectorGen.py` itself
    accepts is available here too, applying uniformly to every system in
    every sector this script generates (see
    `sectorGen.add_shared_generation_options`) -- this script adds only
    the options specific to *which* sectors to generate and where.

    Returns:
        argparse.Namespace: Parsed arguments, plus `sector_name`,
            `system_file`, `num_orbits`, and `name` forced to `None` so
            the namespace is shaped exactly like `sectorGen.generate_sector`
            expects (each generated sector gets its own freshly generated
            name, never a fixed one -- there is no single "the sector"
            this script names, unlike `sectorGen.py`'s own `--name`/`-n`).
    """
    parser = argparse.ArgumentParser(
        description="Galaxy Generation Options",
        epilog="Generates many sectors as one galaxy -- see this script's module docstring for the two "
               "generation modes (--shell batch generation, --center-sector local-neighborhood generation) "
               "and how they build on sectorGen.py/galaxyGeometry.py.",
        prefix_chars='-+')

    parser.add_argument('--version', action=VersionAction, banner=version_banner('galaxyGen.py'))

    sectorGen.add_shared_generation_options(parser)

    mode_group = parser.add_mutually_exclusive_group(required=True)
    mode_group.add_argument('--shell', type=int, metavar='K',
                            help="Batch mode: generate every not-yet-generated sector slot in radial shell K "
                                 "(0-indexed; see docs/design/galaxy-coordinate-system.md section 3).")
    mode_group.add_argument('--center-sector', type=int, metavar='SECTOR_ID',
                            help="Local-neighborhood mode: generate every not-yet-generated sector slot "
                                 "within --radius-pc of the given, already galaxy-placed sector's own "
                                 "stored center.")

    parser.add_argument('--limit', type=int,
                        help="With --shell: generate only the first N not-yet-generated slots of the "
                             "shell, rather than the whole shell.")
    parser.add_argument('--yes', action='store_true',
                        help="With --shell: skip the confirmation normally required before generating a "
                             "shell whose total slot count exceeds LARGE_SHELL_WARNING_THRESHOLD.")
    parser.add_argument('--radius-pc', type=float,
                        help="With --center-sector: the neighborhood search radius, in parsecs.")
    parser.add_argument('--db-path', type=str,
                        help="Path to the SQLite database file sectors are read from and saved to. "
                             "Defaults to stellarObjects._db.DEFAULT_DB_PATH (db/planetgen.db).")

    args = parser.parse_args()

    sectorGen.validate_shared_generation_args(args, parser)

    if args.shell is not None and args.shell < 0:
        parser.error("--shell must be >= 0.")

    if args.center_sector is not None and args.radius_pc is None:
        parser.error("--center-sector requires --radius-pc.")
    if args.radius_pc is not None and args.center_sector is None:
        parser.error("--radius-pc only applies to --center-sector.")
    if args.radius_pc is not None and args.radius_pc <= 0:
        parser.error("--radius-pc must be a positive number.")

    if args.limit is not None and args.shell is None:
        parser.error("--limit only applies to --shell.")
    if args.limit is not None and args.limit < 1:
        parser.error("--limit must be a positive integer.")
    if args.yes and args.shell is None:
        parser.error("--yes only applies to --shell.")

    # sectorGen.generate_sector()/build_sector_configs() expect a namespace
    # shaped like sectorGen.process_args()'s own output -- see this
    # function's docstring for why these are always None here.
    # `output` in particular is read directly by
    # systemGen.build_system_config (`output_path = args.output`) even
    # though this script has no per-system/per-sector output-file option
    # of its own (every generated sector is only ever saved to the
    # database, never rendered to a file/stdout the way sectorGen.py's
    # own CLI does) -- it must exist on the namespace even though its
    # value is never used afterward.
    args.sector_name = None
    args.system_file = None
    args.num_orbits = None
    args.name = None
    args.output = None

    return args


def _edge_pc():
    """
    The (uniform, per this design's scope) sector edge length used for
    every shell/enumeration computation, in parsecs -- derived from
    `program_constants.DEFAULT_SECTOR_EDGE_LY`, the same fixed edge length
    every sector `sectorGen.py`/`SpaceSector` produces today (sector edge
    length is not currently an exposed CLI option anywhere in this
    package).

    Returns:
        float: The sector edge length, in parsecs.
    """
    return ly_to_pc(program_constants.DEFAULT_SECTOR_EDGE_LY)


def _generate_and_save_sector_at(args, shell_index, shell_slot_index, position_pc, edge_pc):
    """
    Generates one sector via `sectorGen.generate_sector` at the given
    galaxy-frame position and shell address, and saves it -- the one
    per-sector unit of work both `run_shell_batch` and
    `run_local_neighborhood` repeat.

    Args:
        args (argparse.Namespace): Parsed arguments (see `process_args`).
        shell_index (int): This sector's shell index.
        shell_slot_index (int): This sector's slot index within that shell.
        position_pc (tuple): `(x, y, z)` in parsecs, this sector's
                             galaxy-frame center (from `sector_position_pc`
                             or an `enumerate_sectors_within_radius`
                             result).
        edge_pc (float): The sector edge length, in parsecs (`_edge_pc`) --
                         threaded in rather than recomputed, since both
                         callers already have it.

    Returns:
        tuple: `(sector_id, sector_name)` of the newly saved sector.
    """
    x, y, z = position_pc
    radius_pc = galactic_radius_pc(position_pc)
    galactic_center_dist_ly = pc_to_ly(radius_pc)

    sector_name, sector = sectorGen.generate_sector(args, galactic_center_dist_ly=galactic_center_dist_ly)

    vertices_pc = relax_vertices(shell_index, shell_slot_index, edge_pc)
    galaxy_position = {
        "center_x_pc": x, "center_y_pc": y, "center_z_pc": z,
        "galactic_radius_pc": radius_pc,
        "shell_index": shell_index, "shell_slot_index": shell_slot_index,
        "vertices_pc": vertices_pc,
    }
    sector_id = _db.save_sector(sector, db_path=args.db_path, galaxy_position=galaxy_position)
    return sector_id, sector_name


def run_shell_batch(args, edge_pc):
    """
    Batch mode: generates every not-yet-generated sector slot in shell
    `args.shell` (up to `args.limit`, if given).

    Args:
        args (argparse.Namespace): Parsed arguments (see `process_args`);
            `args.shell` must not be `None`.
        edge_pc (float): The sector edge length, in parsecs (`_edge_pc`).

    Raises:
        SystemExit: If the shell's total slot count exceeds
                   `LARGE_SHELL_WARNING_THRESHOLD` and neither `--limit`
                   nor `--yes` was given.
    """
    shell_index = args.shell
    total_slots = shell_sector_count(shell_index)

    if total_slots > LARGE_SHELL_WARNING_THRESHOLD and args.limit is None and not args.yes:
        raise SystemExit(
            f"Shell {shell_index} holds {total_slots} sector slots -- generating a whole shell this "
            f"large is likely impractical. Pass --limit N to generate only the first N not-yet-generated "
            f"slots, or --yes to confirm generating all {total_slots}."
        )

    conn = _db.get_connection(args.db_path)
    try:
        occupied = _db.get_occupied_shell_slots(conn, [shell_index])
    finally:
        conn.close()

    generated = 0
    for slot_index in range(total_slots):
        if args.limit is not None and generated >= args.limit:
            break
        if (shell_index, slot_index) in occupied:
            continue

        position_pc = sector_position_pc(shell_index, slot_index, edge_pc)
        sector_id, sector_name = _generate_and_save_sector_at(args, shell_index, slot_index, position_pc, edge_pc)
        generated += 1
        print(f"Saved sector '{sector_name}' at shell {shell_index} slot {slot_index} (sector_id={sector_id}).")

    already_existed = len(occupied)
    print(
        f"Generated {generated} new sector(s) in shell {shell_index} "
        f"({total_slots} total slots, {already_existed} already existed)."
    )


def run_local_neighborhood(args, edge_pc):
    """
    Local-neighborhood mode: generates every not-yet-generated sector slot
    within `args.radius_pc` parsecs of `args.center_sector`'s own stored
    galaxy-frame center.

    Args:
        args (argparse.Namespace): Parsed arguments (see `process_args`);
            `args.center_sector`/`args.radius_pc` must not be `None`.
        edge_pc (float): The sector edge length, in parsecs (`_edge_pc`).

    Raises:
        SystemExit: If `args.center_sector` doesn't exist, or exists but
                   has never been placed in a galaxy (its galaxy-position
                   columns are NULL -- e.g. a sector generated by
                   `sectorGen.py`'s own standalone CLI).
    """
    conn = _db.get_connection(args.db_path)
    try:
        try:
            center_position = _db.get_sector_galaxy_position(conn, args.center_sector)
        except ValueError as exc:
            raise SystemExit(str(exc)) from exc
    finally:
        conn.close()

    if center_position is None:
        raise SystemExit(
            f"sector_id={args.center_sector} has never been placed in a galaxy (its galaxy-position "
            f"columns are NULL) -- --center-sector requires an already galaxy-placed sector (one "
            f"generated via galaxyGen.py itself, not sectorGen.py's standalone CLI). Use --shell to "
            f"generate placed sectors from scratch instead."
        )

    center = (
        center_position["center_x_pc"], center_position["center_y_pc"], center_position["center_z_pc"],
    )
    candidates = list(enumerate_sectors_within_radius(center, args.radius_pc, edge_pc))

    candidate_shells = sorted({shell_index for shell_index, _slot, _x, _y, _z, _dist in candidates})
    conn = _db.get_connection(args.db_path)
    try:
        occupied = _db.get_occupied_shell_slots(conn, candidate_shells)
    finally:
        conn.close()

    generated = 0
    for shell_index, slot_index, x, y, z, distance_pc in candidates:
        if (shell_index, slot_index) in occupied:
            continue

        sector_id, sector_name = _generate_and_save_sector_at(args, shell_index, slot_index, (x, y, z), edge_pc)
        generated += 1
        print(
            f"Saved sector '{sector_name}' at shell {shell_index} slot {slot_index}, "
            f"{distance_pc:.2f} pc from sector_id={args.center_sector} (sector_id={sector_id})."
        )

    already_existed = len(candidates) - generated
    print(
        f"Generated {generated} new sector(s) within {args.radius_pc} pc of sector_id={args.center_sector} "
        f"({len(candidates)} candidate slot(s) found, {already_existed} already existed)."
    )


def main():
    """
    The main entry point for the galaxy generation script.

    Parses command-line arguments, then dispatches to `run_shell_batch` or
    `run_local_neighborhood` depending on which mode was selected (the
    argument parser enforces exactly one of `--shell`/`--center-sector`).
    """
    random.seed(secrets.randbits(128))

    args = process_args()
    edge_pc = _edge_pc()

    if args.shell is not None:
        run_shell_batch(args, edge_pc)
    else:
        run_local_neighborhood(args, edge_pc)


if __name__ == "__main__":
    main()
