# planetgen/galaxy/version_check.py

"""
The mixed-version warning (DB.7; docs/design/reproducible-galaxies.md,
section 5): a galaxy extended by a different release holds sectors made by
more than one version, and such a galaxy reproduces only sector by sector,
each on the version that made it. Every sector records the key, release,
Python and platform that generated it (schema v67), so the check names
exactly what differs.
"""

from planetgen.galaxy import settings_file, version_history, version_key


def differences(running, stored):
    """
    What differs between the running code and the code that made something,
    as phrases such as `Python 3.12.3 now, 3.11.9 when generated`. Each
    argument is a `version_key.current()`-shaped dict; `stored` may be
    `None` or hold `None` values (made before the code was recorded).
    """
    stored = stored or {}
    found = []
    for name, field in (("PlanetGen", "planetgen_version"), ("Python", "python_version"),
                        ("on", "platform")):
        before = stored.get(field)
        if before is None:
            continue
        if before != running[field]:
            found.append(f"{name} {running[field]} now, {before} when generated")
    if not found and stored.get("version_key") not in (None, running["version_key"]):
        found.append(f"version key {running['version_key']} now, {stored['version_key']} when generated")
    return found


def mixed_version_warning(versions, running=None):
    """
    A warning for the galaxy whose sectors came from `versions`
    (`store.sector_versions`), or `None` when every sector with a recorded
    version was made by the running code (or none has a version recorded
    yet, which a plain update cannot tell from a new galaxy).
    """
    running = running or version_key.current()
    lines = []
    for group in versions:
        if group["version_key"] is None or group["version_key"] == running["version_key"]:
            continue
        count = group["sectors"]
        what = "; ".join(differences(running, group)) or "its version key differs"
        lines.append(f"{count:,} sector{'' if count == 1 else 's'}: {what}")
    if not lines:
        return None
    return ("This galaxy holds sectors generated by another version of PlanetGen (" + " | ".join(lines)
            + "). Sectors added now use this version, so the galaxy reproduces only sector by sector, each on "
              "the version that made it.")


def planned_differences(document, running=None, lock_sha256=None):
    """
    What differs between the running code and the code the galaxy was planned
    with, read from its settings file (ADM.18): the same phrases
    `differences` gives, plus `requirements.lock changed` when the pinned
    libraries are not the ones recorded.

    Args:
        document (dict): The settings file's content (`settings_file.build`).
        running (dict, optional): `version_key.current()`.
        lock_sha256 (str, optional): The running `requirements.lock` hash
            (`version_history.requirements_sha256()`).
    """
    running = running or version_key.current()
    planned = document.get("version", {})
    found = differences(running, {
        "planetgen_version": (planned.get("planetgen") or {}).get("version"),
        "python_version": (planned.get("python") or {}).get("version"),
        "platform": planned.get("platform"),
        "version_key": planned.get("version_key"),
    })
    recorded = (document.get("hashes") or {}).get("requirements_lock_sha256")
    if lock_sha256 is None:
        lock_sha256 = version_history.requirements_sha256()
    if recorded and lock_sha256 and recorded != lock_sha256:
        found.append("requirements.lock changed since the galaxy was planned")
    return found


def galaxy_warning(conn):
    """
    OPS.14: the one check behind every mismatch warning (`planetgen galaxy`,
    the Generate page, `planetgen fingerprint`): sectors made by another
    version (`mixed_version_warning`), then how the running code differs from
    the galaxy's settings file. `None` when nothing differs, or when no
    settings file is found (a galaxy planned before ADM.18).
    """
    from planetgen.db import store
    parts = []
    mixed = mixed_version_warning(store.sector_versions(conn))
    if mixed:
        parts.append(mixed)
    seed = store.get_galaxy_seed(conn)
    entry = settings_file.current_file(seed) if seed is not None else None
    if entry is not None:
        try:
            with open(entry["path"], "r", encoding="utf-8") as handle:
                import json
                found = planned_differences(json.load(handle))
        except (OSError, ValueError):
            found = []
        if found:
            parts.append("The running code differs from the galaxy's settings file (" + "; ".join(found) + ").")
    return " ".join(parts) or None
