# planetgen/galaxy/version_check.py

"""
The mixed-version warning (DB.7; docs/design/reproducible-galaxies.md,
section 5): a galaxy extended by a different release holds sectors made by
more than one version, and such a galaxy reproduces only sector by sector,
each on the version that made it. Every sector records the key, release,
Python and platform that generated it (schema v67), so the check names
exactly what differs.
"""

from planetgen.galaxy import version_key


def differences(running, stored):
    """
    What differs between the running code and the code that made something,
    as phrases such as `Python 3.12.3 now, 3.11.9 when generated`. Each
    argument is a `version_key.current()`-shaped dict; `stored` may be
    `None` or hold `None` values (made before the code was recorded).
    """
    stored = stored or {}
    found = []
    for name, field in (("PlanetGen", "planetgen_version"), ("Python", "python_version"),
                        ("on", "platform")):
        before = stored.get(field)
        if before is None:
            continue
        if before != running[field]:
            found.append(f"{name} {running[field]} now, {before} when generated")
    if not found and stored.get("version_key") not in (None, running["version_key"]):
        found.append(f"version key {running['version_key']} now, {stored['version_key']} when generated")
    return found


def mixed_version_warning(versions, running=None):
    """
    A warning for the galaxy whose sectors came from `versions`
    (`store.sector_versions`), or `None` when every sector with a recorded
    version was made by the running code (or none has a version recorded
    yet, which a plain update cannot tell from a new galaxy).
    """
    running = running or version_key.current()
    lines = []
    for group in versions:
        if group["version_key"] is None or group["version_key"] == running["version_key"]:
            continue
        count = group["sectors"]
        what = "; ".join(differences(running, group)) or "its version key differs"
        lines.append(f"{count:,} sector{'' if count == 1 else 's'}: {what}")
    if not lines:
        return None
    return ("This galaxy holds sectors generated by another version of PlanetGen (" + " | ".join(lines)
            + "). Sectors added now use this version, so the galaxy reproduces only sector by sector, each on "
              "the version that made it.")
