#!/usr/bin/env python3
"""
Writes `src/planetgen/db/models.py`: SQLAlchemy `Table` declarations for
every table in `planetgen/db/schema.sql` (DB.11).

It builds a scratch database from `schema.sql`, reflects it, and renders
what SQLAlchemy finds. Run it after changing `schema.sql`:

    python scripts/generate_db_models.py

`tests/test_db_models.py` fails when `models.py` no longer matches a database
built from `schema.sql`, which is also what keeps new Alembic revisions
honest. Needs a MySQL/MariaDB account that can create databases (the
`PLANETGEN_MYSQL_*` variables, as everywhere else).
"""

import os
import sys
import uuid

import pymysql
import sqlalchemy as sa

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT = os.path.join(ROOT, "src", "planetgen", "db", "models.py")
SKIP_TABLES = {"alembic_version"}

HEADER = '''# planetgen/db/models.py
#
# GENERATED by scripts/generate_db_models.py from planetgen/db/schema.sql.
# Do not edit by hand: change schema.sql (and add an Alembic revision), then
# rerun the script. tests/test_db_models.py checks this file against a
# database built from schema.sql.

"""
The content database's tables as SQLAlchemy `Table` objects on `metadata`
(DB.11). Alembic compares a live database against this (`compare_metadata`),
and migrations can refer to the tables by name.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

metadata = sa.MetaData()
'''


def render_type(type_):
    """Source text for a reflected column type, as a `mysql.` type."""
    kind = type(type_).__name__
    args = []
    length = getattr(type_, "length", None)
    if length is not None:
        args.append(repr(length))
    if getattr(type_, "unsigned", False):
        args.append("unsigned=True")
    fsp = getattr(type_, "fsp", None)
    if fsp:
        args.append(f"fsp={fsp}")
    if kind == "VARCHAR":
        return f"sa.String({', '.join(args)})"
    if kind == "TEXT":
        return "sa.Text()"
    return f"mysql.{kind}({', '.join(args)})"


def render_column(col):
    parts = [repr(col.name), render_type(col.type)]
    if col.computed is not None:
        parts.append(f"sa.Computed({str(col.computed.sqltext)!r}, persisted={bool(col.computed.persisted)})")
    elif col.server_default is not None:
        parts.append(f"server_default=sa.text({str(col.server_default.arg)!r})")
    if col.primary_key:
        parts.append("primary_key=True")
    if col.autoincrement is True:
        parts.append("autoincrement=True")
    parts.append(f"nullable={col.nullable}")
    return f"    sa.Column({', '.join(parts)}),"


def render_table(table):
    lines = [f"{table.name} = sa.Table(", f"    {table.name!r},", "    metadata,"]
    lines += [render_column(col) for col in table.columns]
    for index in sorted(table.indexes, key=lambda i: i.name):
        columns = ", ".join(repr(c.name) for c in index.columns)
        extra = ""
        if index.unique:
            extra += ", unique=True"
        prefix = index.dialect_options["mysql"]["prefix"]
        if prefix:
            extra += f", mysql_prefix={prefix!r}"
        lines.append(f"    sa.Index({index.name!r}, {columns}{extra}),")
    for constraint in sorted(table.constraints, key=lambda c: str(c.name)):
        if isinstance(constraint, sa.ForeignKeyConstraint):
            local = [c.name for c in constraint.columns]
            remote = [f"{e.column.table.name}.{e.column.name}" for e in constraint.elements]
            extra = f", name={constraint.name!r}"
            if constraint.ondelete:
                extra += f", ondelete={constraint.ondelete!r}"
            if constraint.onupdate:
                extra += f", onupdate={constraint.onupdate!r}"
            lines.append(f"    sa.ForeignKeyConstraint({local!r}, {remote!r}{extra}),")
        elif isinstance(constraint, sa.CheckConstraint):
            lines.append(f"    sa.CheckConstraint({str(constraint.sqltext)!r}, name={constraint.name!r}),")
    lines.append('    mysql_engine="InnoDB",')
    lines.append(")")
    return "\n".join(lines)


def render_models(metadata):
    tables = sorted((t for t in metadata.tables.values() if t.name not in SKIP_TABLES), key=lambda t: t.name)
    return HEADER + "\n\n" + "\n\n\n".join(render_table(t) for t in tables) + "\n"


def reflect_schema(config):
    """A `MetaData` reflected from a new database `config` points at,
    built from `schema.sql`."""
    sys.path.insert(0, os.path.join(ROOT, "src"))
    from planetgen.db import store
    store.get_connection(config).close()
    engine = sa.create_engine(
        "mysql+pymysql://",
        creator=lambda: pymysql.connect(host=config.host, port=config.port, user=config.user,
                                         password=config.password, database=config.database),
    )
    try:
        metadata = sa.MetaData()
        metadata.reflect(engine)
    finally:
        engine.dispose()
        store.close_pool(config)
    return metadata


def main():
    sys.path.insert(0, os.path.join(ROOT, "src"))
    from planetgen.db import store
    base = store.DEFAULT_MYSQL_CONFIG
    name = f"planetgen_models_{uuid.uuid4().hex[:12]}"
    admin = pymysql.connect(host=base.host, port=base.port, user=base.user, password=base.password)
    try:
        admin.cursor().execute(f"CREATE DATABASE `{name}`")
        config = store.MySQLConfig(host=base.host, port=base.port, user=base.user, password=base.password,
                                   database=name)
        try:
            source = render_models(reflect_schema(config))
        finally:
            admin.cursor().execute(f"DROP DATABASE `{name}`")
    finally:
        admin.close()
    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write(source)
    print(f"wrote {os.path.relpath(OUTPUT, ROOT)}")


if __name__ == "__main__":
    main()
